### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by LBeezy** [maorninja/Guide#1]
secret_sector.bin

**Comment by NightScript370** [comment]
Huh? More information please. On part 2? I'm rewritting that to use CTRBootManager9.

Please give more information.

**Comment by LBeezy** [comment]
Every time i try to run the ShadowNAND  installer it says secret_sector.bin doesn't exist or has wrong size.

**Comment by NightScript370** [comment]
Did you install the other files?

Oh. I see now. ShadowNAND installer changed the path. Until the new guide comes out, please follow these steps:
1. Copy everything from `homebrew\a9lh` to `SD:/homebrew/3ds/ShadowNAND_Installer/`
2. Try again
3. Follow the rest

Also, Part 4 (now part 3) is currently a non-functional link. And Part 3 (Now part 2) needs another update. I'm changing stuff real quick for you.

**Comment by LBeezy** [comment]
oh ok thanks.

**Comment by NightScript370** [comment]
Did it work?

**Comment by LBeezy** [comment]
i dont understand this part right here
1. On your SD card, rename sdmc:/homebrew/3ds/boot.bin to boot_old.bin
2. Copy boot.bin to sdmc:/homebrew/3ds/boot.bin

i don't got a boot.bin in homebrew/3ds

**Comment by NightScript370** [comment]
Its not your fault. Its mine.

Basically, what the old guide was to put boot.bin in `\homebrew`. But now, it must be `homebrew\3ds\` I haven't applied it yet. But first copy `\homebrew\boot.bin` to `homebrew\3ds\boot.bin`. After that, continue the guide.

Also, for #2, its with the developer build of Luma3DS.

**Comment by LBeezy** [comment]
so i switch from regular to dev?

**Comment by NightScript370** [comment]
Temporarily, yes.

**Comment by LBeezy** [comment]
got to work to work, thank you.
