### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by jmx077** [maorninja/Guide#11]
so I was wondering does this still work can I do this with a 3ds rom to make it in to a cia on 11.30 cfw?

**Comment by NightScript370** [comment]
It does work, but there is a better way of doing it now...

So if you have Decrypt9, just use the function of "Convert .3ds to .cia" It was recently added...

**Comment by jmx077** [comment]
im new to this stuff I dont understand :(

**Comment by NightScript370** [comment]
Okay, so how did you get CFW?

**Comment by jmx077** [comment]
by using a guide

**Comment by NightScript370** [comment]
Which guide, to be specific?

Is it this one: https://3ds.guide/

???

**Comment by jmx077** [comment]
yes that one

**Comment by NightScript370** [comment]
Okay, so now, you'll need to hold Start, and go to the SD card files, find your 3DS ROM and press the convert button...

**Comment by jmx077** [comment]
that easy???

**Comment by NightScript370** [comment]
Yep, its that easy. You can give thanks to plailect and d0k3.

**Comment by jmx077** [comment]
how do I do that?

**Comment by NightScript370** [comment]
https://github.com/Plailect/Guide/issues - Here's to thank plailect for helping you install CFW and GodMode9
https://github.com/d0k3/GodMode9/issues - Here's tp thank d0k3 for making the converter super easy to use....

**Comment by jmx077** [comment]
ok cool thank you for your help :) will go thank you in a few mins
